# Site settings
title: VietOpenStack Blog 
description: Trang blog của cộng đồng VietOpenStack - quản lý bởi VietStack Team
#baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
baseurl: ""
url: "https://blog.vietstack.vn" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
enforce_ssl: blog.vietstack.vn

# User settings
username: VietStack
user_description: VietStack 
user_title: Blog của cộng đồng VietOpenStack - quản lý bởi VietStack Team
email: contact@vietstack.vn
twitter_username: vietstack
github_username:  vietstack
gplus_username:  vietstack
disqus_username: vietstack
facebook_username: vietstack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
