# Site settings
title: ZZANZU
description: A blog about a person Chanjoo Lee
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zzanzu.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ZZANZU
user_description: Chanjoo Lee
user_title: Chanjoo Lee
email: lees3301@gmail.com
twitter_username: chanjoo2
github_username:  zzanzu
gplus_username: lees3301
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
