# Site settings
title: 100 Days of Developer eXperience 
description: Daily unfiltered, opinionated and arrogant post on DX for 100 days starting 13th July 2019
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kyyberi.github.io/100daysofDX" 

# User settings
username: 100 Days of Developer eXperience
user_description: Jarkko "APItalist" Moilanen
user_title: Random thoughts on DX for 100 days
email: jarkko@vimo.fi
twitter_username: Jarkko_Moilanen
github_username:  kyyberi
disqus_username: jarkkomoilanen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me & site
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
